### ISSUE TITLE
Duplicate symbol CharSet

### ISSUE THREAD

**Issue by clausecker** [rwestlund/freesweep#11]
When compiling with a sufficiently modern C compiler (one where `-fno-common` is the default), linking fails due to a duplicate symbol `CharSet`.  This is because the global variable `CharSet` is defined in `sweep.h.in` which is included in all sorts of files.  To fix this issue, change the declaration to

    extern DrawChars CharSet;

and in exactly one source file place a definition

    DrawChars CharSet;

**Comment by clausecker** [comment]
The same also applies to `DebugLog` if that feature is enabled.

**Comment by rwestlund** [comment]
Charset issue fixed by #8, available in new tag v1.0.2

**Comment by clausecker** [comment]
Note that you did not fix `DebugLog`, so the build will still fail if that is enabled.

**Comment by rwestlund** [comment]
Oh, good catch. I'll merge a PR if you want to make one.

**Comment by digitalcombine** [comment]
The DebugLog issue was fixed by #15.
